4529 Add descriptive date fields to response from get_project_status_for_user_api
THIS-Institute/thiscovery-core pull request #180
Opened 2022-04-21 14:14 UTC by sophiemachin

Add descriptive date fields to response from get_project_status_for_user_api

2022-04-21 14:16 UTC, sophiemachin commented
@this-andy I'm worried that the three new fields are making the payload unnecessarily large. 

Do you know which fields are required by the front end? Maybe we can only return that (for example only return `earliest_start_date_desc`)

2022-04-22 09:38 UTC, sophiemachin commented
@this-andy This is ready for re-review. I've added the extra tests you mentioned yesterday, added formatting and removed the overrides from the payload

2022-04-22 10:27 UTC, this-andy requested changes

2022-04-22 10:27 UTC, this-andy commented on api/endpoints/project.py
> +                    return dt.fromisoformat(d).strftime("%d-%m-%Y, %H:%M")
Could we make this format string a constant at the top of project.py - 'default data format' or similar.
And can we make month mmmm (April) rather than mm (04)

2022-04-22 12:18 UTC, sophiemachin commented on api/endpoints/project.py
> +                    return dt.fromisoformat(d).strftime("%d-%m-%Y, %H:%M")
@this-andy I think I've made the required change, but I'm currently in the middle of some database changes for another ticket so I can't easily run the test suite. I'll run the test suite before I merge.

2022-05-03 11:42 UTC, sophiemachin commented
@this-andy This is ready for re-review. The tests now pass. Weirdly some files have crept into this PR from group_test_id PR, you can ignore these because they are the same as master.

2022-05-03 14:12 UTC, this-andy approved these changes

2022-05-03 15:17 UTC, merged