Alistair/4705 populate user last login from auth0 events
THIS-Institute/thiscovery-core pull request #203
Opened 2022-08-25 15:27 UTC by alistairclark

A few notes

* Not 100% sure if it's safe to assume that the `user_name` field in the auth0 event can be assumed to always refer to the email of the user, but I believe it can
* Worth double checking that the event time I'm using for the last login is correct.
* I've assumed that the only type of auth0 event we consider a successful login is "s"

2022-08-26 10:06 UTC, afs25 requested changes
Good job. See the comments for requested changes.

2022-08-26 10:06 UTC, afs25 commented on template.yaml
> +            TableName: !Ref Auth0Events
This will fail because there is no Auth0Events table defined in this template.

2022-08-26 10:06 UTC, afs25 commented on template.yaml
> +                    - w
This list should have only "s". We don't need to invoke the lambda for any other types.

2022-08-26 10:06 UTC, afs25 commented on template.yaml
> +            StackeryName: UserRecordLastLoginRule
This is not needed (because we don't use Stackery anymore).

2022-08-26 10:06 UTC, afs25 commented on template.yaml
> +            EventBusName: !Ref EnvConfigeventbridgeauth0eventbusAsString
This needs to be added to the Parameters section of the template

2022-09-06 10:58 UTC, this-andy commented on .gitignore
> +.vscode/
This method of exclusion from GitHub looks different from how we have done this in other repos.  Not a blocker, but let's discuss at team meeting and agree best approach.

2022-09-06 11:19 UTC, this-andy commented on api/endpoints/user.py
> +    assert detail_type == "Auth0 log", f"Unexpected detail-type: {detail_type}"
Not sure that we should be using assert in this way in production code.  I'd prefer to see check within try/except.
Again, let's discuss use of assert in meeting tomorrow

2022-09-06 11:21 UTC, this-andy commented on api/tests/test_data/user_data_PSFU.csv
> +d1070e81-557e-40eb-a7ba-b951ddb7ebdc,2018-08-17 12:10:56.798192+00,2018-08-17 12:10:56.833885+00,altha@email.co.uk,Mrs,Altha,Alcorn,,,GB,,2018-08-17 12:10:56.833885+00
Would be good to have at least one of these with a null value, as this will happen in real world.

2022-09-06 11:24 UTC, this-andy requested changes
Would also like to get Sophie and/or Andre to comment on this PR as they have worked in these area more recently than me

2022-09-07 12:31 UTC, afs25 commented on api/tests/test_scripts/unit_tests/test_user.py
> +            self.assertEqual(HTTPStatus.NO_CONTENT, result["statusCode"])
This doesn't make sense. The expected result should be the same on AWS or locally.

2022-09-07 13:36 UTC, alistairclark commented
There are still tests which fail in this repo, but none appear to be related to my changes. 

With `TEST_ON_AWS = True` I get

```
======================================================================
FAIL: test_user_task_url_update_ok (test_user_task.TestUserTaskRedirectToInterview)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/alistair/python-projects/thiscovery-core/api/tests/test_scripts/unit_tests/test_user_task.py", line 634, in test_user_task_url_update_ok
    self.assertEqual(
AssertionError: 'https://test-afs25-video.thiscovery.org?[44 chars]6j29' != None
```

With `TEST_ON_AWS = False` `test_project_status_for_user_default.test_user_c_project_status` fails because the real/expected URLs in a dictionary are not equal.

2022-09-07 16:07 UTC, afs25 approved these changes

2022-09-08 11:34 UTC, this-andy approved these changes

2022-09-08 13:26 UTC, merged