Alistair/4706 dyanmic reminders about survey tasks
THIS-Institute/thiscovery-core pull request #209
Opened 2022-09-13 13:12 UTC by alistairclark

2022-09-26 10:47 UTC, this-andy requested changes

2022-09-26 10:47 UTC, this-andy commented on api/endpoints/common/sql_queries.py
> +            utr.created >= '{datetime_since_reminder_sent}'
Can we ensure we don't send two inactivity reminders for same task

2022-09-28 15:13 UTC, this-andy requested changes

2022-09-28 15:13 UTC, this-andy commented on api/endpoints/common/sql_queries.py
> +        WHERE
This looks like it will result in multiple reminders being sent for an individual task - every HOURS_SINCE_LAST_REMINDER_SENT.  Am I reading it right (it's kind of difficult to be certain of the exact behaviour of SQL when it's complex like this).
I think it is ok to send multiple reminders for different tasks (as we discussed in meeting a few days ago), but not multiple reminders for a single task.

2022-09-28 15:13 UTC, this-andy commented on api/endpoints/user_task_reminder.py
> +    datetime_since_reminder_sent = datetime.utcnow() - timedelta(
Can you remind me what this does?  What does it represent.  It may be that my confusion comes from the name - does it describe its purpose well?

2022-10-03 13:10 UTC, alistairclark commented on api/endpoints/user_task_reminder.py
> +    datetime_since_reminder_sent = datetime.utcnow() - timedelta(
Good point, the name here really isn't clear. I'll change it. 

The variable refers to the window of time within which we're looking for any other reminders being sent.

2022-10-03 15:02 UTC, alistairclark commented on api/endpoints/user_task_reminder.py
> +    datetime_since_reminder_sent = datetime.utcnow() - timedelta(
I've renamed the variable slightly and added some comments to explain what these variables do. If you've got any thoughts on a better name then let me know though.

2022-10-03 15:03 UTC, alistairclark commented on api/endpoints/common/sql_queries.py
> +        WHERE
I've been trying to add as many scenarios in the tests as I can because I agree the query is hard to follow. There's a test that covers this case though.

https://github.com/THIS-Institute/thiscovery-core/pull/208/files#diff-30f1a72674d74c7258c82c771e3e687f02a78268d9b5d07b431265bc553e891dR124

2022-10-04 09:38 UTC, this-andy commented on api/endpoints/common/sql_queries.py
> +        WHERE
Yes, I agree, that SQL looks like it will give the behaviour we want.  Thanks for clarifying

2022-10-04 09:40 UTC, this-andy approved these changes

2022-11-15 10:21 UTC, merged