Setup CI/CD
THIS-Institute/thiscovery-core pull request #215
Opened 2022-11-02 11:13 UTC by sophiemachin

2022-11-02 11:49 UTC, this-andy commented on api/tests/test_scripts/unit_tests/test_project_status_for_user.py
> +import testing_utilities as test_utils  # this should be the first import; it sets env variables
What's the implication of this comment - should import be moved, and if so why hasn't't it?

2022-11-02 11:50 UTC, this-andy commented on api/tests/test_scripts/unit_tests/test_project_status_for_user.py
> +import testing_utilities as test_utils  # this should be the first import; it sets env variables
Or does it no longer apply?

2022-11-02 12:20 UTC, sophiemachin commented on api/tests/test_scripts/unit_tests/test_project_status_for_user.py
> +import testing_utilities as test_utils  # this should be the first import; it sets env variables
Good question. It seems I accidentally moved it, but it still works

2022-11-02 12:29 UTC, sophiemachin commented on api/tests/test_scripts/unit_tests/test_project_status_for_user.py
> +import testing_utilities as test_utils  # this should be the first import; it sets env variables
My instinct is to just put it back so it doesn't break anything, but we should probably put more thought into why Andre wanted it first. I can't find the US for this bit of work unfortunately

2022-11-03 10:17 UTC, sophiemachin commented on api/tests/test_scripts/unit_tests/test_project_status_for_user.py
> +import testing_utilities as test_utils  # this should be the first import; it sets env variables
I've put it back

2022-11-08 10:30 UTC, alistairclark requested changes
I think you'll need to rewrite `actions-run-tests` to take pythonpath as an arguement/environment variable so that it can be configured per project. It could default to `src` as that seems to be the default now.

I don't think it's sustainable to have separate branches for each project that uses the action. For example if version 0.5 sets a different path on a different branch, then 0.6 on master would be a later version but without any of the changes from 0.5. Could get tangled up pretty quickly!

After that I think you should revert all the changed imports in this PR. I got the old paths working with this path on `actions-run-test` https://github.com/THIS-Institute/actions-run-tests/blob/alistair/core_run_tests_action/action.yml#L10.

2022-11-08 10:30 UTC, alistairclark commented on .github/workflows/feature.yaml
> +        uses: THIS-Institute/actions-run-tests@v0.5
I think `actions-run-tests` should be rewritten so you can pass in the python path you want to set before the tests are run. This would make the action more re-usable across different repos. It looks like you can do that (detailed here: https://docs.github.com/en/actions/using-workflows/reusing-workflows).

2022-11-08 15:03 UTC, sophiemachin commented on .github/workflows/feature.yaml
> +        uses: THIS-Institute/actions-run-tests@v0.5
I reverted the imports with the new PYTHONPATH and it works. I did a bit of tidying of the imports, so I've left those changes. If you'd prefer them to be in a different PR that's fine.

2022-11-08 15:55 UTC, alistairclark commented on api/tests/test_scripts/unit_tests/test_user.py
> +            - the login notification triggered by user.get_user_by_id works
Does this need to be reverted too?

2022-11-08 15:55 UTC, alistairclark commented on api/tests/test_scripts/testing_utilities.py
> +from common.pg_utilities import truncate_table_multiple
Should the imports here be reverted back as well?

2022-11-08 16:05 UTC, sophiemachin commented on api/tests/test_scripts/unit_tests/test_user.py
> +            - the login notification triggered by user.get_user_by_id works
Fixed

2022-11-08 16:52 UTC, alistairclark approved these changes
Looking good!

2022-11-10 15:34 UTC, this-andy approved these changes

2022-11-10 15:46 UTC, merged