4869 Add test data for UserList table
THIS-Institute/thiscovery-core pull request #233
Opened 2023-03-10 09:46 UTC by sophiemachin

See https://github.com/THIS-Institute/thiscovery_admin/pull/53 for the work to add the table

2023-03-10 09:46 UTC, this-andy commented
https://this.tpondemand.com/entity/4869

2023-03-10 14:38 UTC, alistairclark approved these changes

2023-03-10 15:05 UTC, this-andy approved these changes

2023-03-31 15:31 UTC, this-andy requested changes

2023-04-03 08:30 UTC, sophiemachin commented on api/local/database-view-sql/view_user_list_for_user_groups.sql
> +    LEFT JOIN projects_project p ON ug.project_id = p.id;
Ah ok, I misunderstood this. Yes it's currently returning rows where project_id isn't set, I'll change that.

2023-04-06 09:39 UTC, this-andy approved these changes

2023-04-06 11:47 UTC, merged